seeds: [0]
models:
  - repo_id: Qwen/Qwen2.5-3B-Instruct
    revision: aa8e72537993ba99e69dfaafa59ed015b17504d1
    quantization: none
  - repo_id: Qwen/Qwen2.5-7B-Instruct
    revision: a09a35458c702b33eeacc393d103063234e8bc28
    quantization: nf4
  - repo_id: allenai/OLMo-2-0425-1B-Instruct
    revision: 48d788eca847d4d7548f375ad03d3c9312f6139e
    quantization: none
